"""Added  table

Revision ID: 88ab440d4e7f
Revises: f758b64ceb66
Create Date: 2023-11-02 21:30:57.696811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ab440d4e7f'
down_revision: Union[str, None] = 'f758b64ceb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_setup', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_setup')
    # ### end Alembic commands ###
